setScene("introduccion","estacion2.png","1.png","ayudarla","vamos"," te mira entre sorbidos.");
setScene("ayudarla","estacion2.png","2.png","ayudarla","vamos","inclinas hacia ella y le preguntas que le sucede, aun llorando ella responde: -Sólo pasaba por el parque y me caí, ¡mi rodilla duele mucho! – -Déjame ver-  respondes mientras llevas tus manos a su herida, de tu bolsa sacas un paño con el que limpias  la raspadura - ¡Duele! – la chica se estremece mientras la tocas, su falda se desliza un poco y tu mirada se desvía levemente hacia su regazo, pero retomas el control, sin embargo tu cara se colora cuando ambos encuentras sus miradas, ella está sonrojada también, con un poco de sobre salto te alejas – ya… ya… esta, ¿crees poder levantarte?- ella asiente y trate de levantarse pero resbala, rápidamente detienes su caída y le ayudas a ponerse de pie.");
setScene("vamos","Bosque3.png","3.png","continuar","ayudarla","vamos… te llevaré hasta la estación del camión ¿está bien? -preguntas mientras señalas el rumbo- -  gracias ¡eres muy amable! - responde la chica mientras se sujeta fuertemente de tu brazo Caminas ayudando a la extraña con cada paso ella tropieza un poco y su cuerpo roza con el tuyo, notas el calor de su cuerpo y lo terso de su piel, tratas de concéntrate en el camino.  Un paso en falso la lleva a jalar fuertemente de tu camisa y un gran quejido por el dolor de su pierna resuena en tus oídos, aun así, logras balancearte y evitar que ambos caigan -lo siento, casi te hago caer, oh, pero eres muy fuerte- -no es nada… eres muy ligera- respondes con una sonrisa bonachona. Continúan con el camino sus tropiezos son constantes y hacen el camino difícil, pero puedes ver la estación del autobús al frente, el autobús esta llegando y temes no llegar antes de que este parta.");
setScene("continuar","Bosque3.png","4.png","ayudarla","vamos","Tratas de apresurarte para alcanzar el camión, parece que no lo lograrás, la preocupación comienza a rebasarte, pues sabes que atardece y el parque es inseguro por la noche, te detienes un segundo y miras a la chica que te devuelve la mirada, enrojecida por el dolor y sus delicados labios exhalan pesadamente su aun prístino aliento, no puede más. En ti surge un aplomo oculto y sujetas su cuerpo con firmeza pero ternura, tu otro brazo baja hasta sus piernas y la levantas por completo, ella se acurruca en tus brazos y en su semblante hay una excitación palpable mientras la cargas hacia el autobús, el conductor detiene y abre la puerta te mira directo en los ojos y te hace un gesto que de aceptación, casi por telepatía puedes escuchar su frase en su mente con una voz profunda y varonil -Hoy es noche de entierro campeón. …el autobús lega a su casa y en un apasionado y ruidoso despliegue la desvistes mientras la besas pasando tus manos por su cuerpo y… te … la … coges..., que digo te la coges, te la turbo coges, no mames estas que la revientas, la destrozas, la partes en ocho, los vecinos llaman a la policía, a los bomberos, al papa, al chapulín clorado, nada te detiene, y es todo lo que siempre soñaste, ella hace de todo, y es una chica-gato, o pony, o tiene verga, o genitales de dragón, ¿yo que sé? lo que te guste, igual te va a cortar el cuello mientras duermes y arrojará tu cuerpo en una fosa en el parque como todas sus víctimas.  DOESN'T MATTER HAD SEX END.");
setScene("adelantarse","Bosque3.png","5.png","ayudarla","vamos","la prisa te rebasa, sabes que los autobuses tardan demasiado en llegar a la estación, y no quieres arriesgarte a ser victima de un asalto, sueltas a la chica y te apresuras hacia el camión con la esperanza de detenerlo  y que quizá ella también pueda subir, cuando estas por detenerte frente a la calle sientes un empujón en las espalda que te hace caer hacia los autos, tratas de levantarte rápido pero es demasiado tarde, las placas de un pesero pitara se impactan en tu cara, golpeando después todo tu cuerpo, que sale despedido hacia la calle, la tertulia se comienza a juntar a tu alrededor murmullos por todos lados, -se suicidó- escuchas por un lado -se tropezó- por otro lado, entre la multitud identificas a la muchacha que trata de ocultar su  sonrisa torcida. CAR CRASH END.");
setScene("sola","Bosque3.png","6.png","ayudarla","vamos","-Creo que puedes sola- dices mientras te apartas -sí, creo que sí, gracias, me las arreglare - te responde la jovencita entre quejidos. Te dispones a continuar con tu camino, pero observas algo extraño en los matorrales detrás de donde se encuentra la chica, es algo rojo o rasado que se arrastra sobre sale de la tierra, fijas tu vista en ello y puedes reconocer el objeto, son dedos, es una mano, cubierta de sangre y tierra, desconcertado miras a la muchacha que entre tanto se te abalanza y antes de que puedas reaccionar un agudo y frio dolor en tu estomago llama tu atención, tu mirada se fija en la hoja de un gran cuchillo, sientes el tiempo detenido mientras el dolor se agudiza y un hormigueo en tu interior delata la profusa hemorragia, la chica ríe maniacamente mientras caes al suelo por el dolor, ella se coloca sobre ti, tu sangre salpica su cara , y tus sentidos se obscurecen en la horrible visón de la mujer acuchillando tu cuerpo.  BLOODY END.");
setScene("alejarte","Bosque3.png","7.png","ayudarla","vamos","Das un paso atrás y continuas con tu camino, pronto llegas a tu casa, entras a tu habitación y cierras la puerta, continuas con tus labores hasta la noche y duermes para levantarte a continuar tu rutina día tras día, año tras año, hasta que estas viejo y solo en la misma habitación preguntándote que habría pasado si hubieras invertido en bitcoin a tiempo… ah sí,  y lo de la chica del parque también… no puedes hilar bien los pensamientos porque padeces de arterioesclerosis y demencia senil.  FOR EVER ALONE END.");




